INSERT INTO datalakepoc_metadata.table_definition values(0,'S_D105003_CAONL_MST_HIST','Current Account master','DATALAKE_POC','¦','csv','1','1','trundate-load','S_D105003_CAONL_MST_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(1,'S_D105007_CAMTRN_HIST','Current Account Transaction','DATALAKE_POC','','xml','1','1','incremental','S_D105007_CAMTRN_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(2,'S_D106001_TCISCUST_HIST','CIS Customer Master','DATALAKE_POC','|','csv','1','1','trundate-load','S_D106001_TCISCUST_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(3,'S_D106002_TCISPERS_HIST','CIS Customer Personal','DATALAKE_POC','|','csv','1','1','incremental','S_D106002_TCISPERS_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(4,'S_D106006_TCISPRDSERV_HIST','CIS Customer Product Master','DATALAKE_POC','|','csv','1','1','trundate-load','S_D106006_TCISPRDSERV_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(5,'S_D113003_DQHIST_TRAN_HIST','Savings Account Transaction','DATALAKE_POC','|','csv','1','1','incremental','S_D113003_DQHIST_TRAN_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(6,'S_D113007_DQONL_MST_HIST','Savings Account Master','DATALAKE_POC','|','csv','1','1','trundate-load','S_D113007_DQONL_MST_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(7,'S_D118001_FTAUTH_HIST','Giro Authorization Master','DATALAKE_POC','|','csv','1','1','trundate-load','S_D118001_FTAUTH_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(8,'S_D118003_FTSIMAS_HIST','GIRO SI ','DATALAKE_POC','|','csv','1','1','incremental','S_D118003_FTSIMAS_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(9,'S_D110006_AMNA_HIST','Card Account Demographics Master','DATALAKE_POC','|','csv','1','1','trundate-load','S_D110006_AMNA_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(10,'S_D110001_AMBS_HIST','Card Master','DATALAKE_POC','|','csv','1','1','trundate-load','S_D110002_AMED_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(11,'S_D110028_ATPT_HIST','Card Transaction ','DATALAKE_POC','|','csv','1','1','incremental','S_D110028_ATPT_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(12,'S_D110002_AMED_HIST','Card Master','DATALAKE_POC','|','csv','1','1','trundate-load','S_D110002_AMED_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(13,'S_D136003_CENTITYDOC_HIST','Finacle to CIS linkage','DATALAKE_POC','|','csv','2','1','trundate-load','S_D136003_CENTITYDOC_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(14,'S_D105014_PCMSTMAIN_HIST','Parameter File link Acct to CIS Cust','DATALAKE_POC','|','csv','2','1','trundate-load','S_D105014_PCMSTMAIN_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(15,'S_D999001_CC_DEFAULT_HIST','Credit_Default','DATALAKE_POC',',','excel','1','1','trundate-load','S_D999001_CC_DEFAULT_HIST');
INSERT INTO datalakepoc_metadata.table_definition values(16,'S_D136002_CMG_HIST','Finacle Customer Master','DATALAKE_POC','|','csv','1','1','trundate-load','S_D136002_CMG_HIST');